---
creation_rules:
- path_regex: secret.sops.yaml
  unencrypted_regex: "^(kind)$"
  age: >-
    age1deg9tqt7jtddnqme6nvcl72czns80z0n25u8k9pw5830dn4arsks5pua4h
- path_regex: provision(\\|/).*\.sops\.ya?ml
  unencrypted_regex: "^(kind)$"
  age: >-
    age1deg9tqt7jtddnqme6nvcl72czns80z0n25u8k9pw5830dn4arsks5pua4h
- path_regex: cluster(\\|/).*\.sec\.(ya?ml|json)
  encrypted_regex: "^(data|stringData)$"
  age: >-
    age1deg9tqt7jtddnqme6nvcl72czns80z0n25u8k9pw5830dn4arsks5pua4h
- path_regex: cluster(\\|/).*\.sops\.ya?ml
  age: >-
    age1deg9tqt7jtddnqme6nvcl72czns80z0n25u8k9pw5830dn4arsks5pua4h
