apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_PASSWORD: AgB26pheOUlhjwH7D3g9ZC8MRKPa3jm9Z/kfs5QMV1i+FgZOlaI3sLIFqI8G55npJcZWnC8d72ocXqXevLGKSl0Xh8fX/GJY/rrFbQ6OP0zl8Ps9fr1cLdnWUWkPAR3jfgNx3bT/xhPpD/lngodDEULzIOkOQuQmZ8gBUn3mMdkrSnX0UJ+MzqLT8qWUx9gV6/fYD/vGKthjDu23JFLc5WENo57BKG7Xd4ZyLR6Oe30gkpH8QfHpV9wBD0+0Xs+kCG6YCEiCXT5w2GZclPXMX2utJcLBNCGqMnLFdEEYheGeRmcb4pu7ZHvjKElDc1iP/ZnS/WeHzwPz13WqpItadR4VNTTVwGh8tWAcA9fyw4tvTvonEIYhLM0jQicEBcZ0SQ6X+3LIC0rEfWf91wguDzDA097SO9CnVS9ELCmsIAuo/GjNvr6KuDhvDQvb+ZAfRDjg402olZR9KMiZ5J/hd/EJaCPSzJacdgKEEiJqq67pUoAYYa7ccdVI0P5RHfj/xcez+Id3yEVbKKRaxQXc0RtBvsVJ0q5l9f041wzY9qcX+R5sCHeVqQThMBmUWsq3x9hoCumaHsB9kVsMJPKLgPMX4cOxWX3w1Au/ckhnP/oqeT1nQS1lQccbfHp3/jilx5Axycap1G5yOIFP/ypoEyB1GEgvjT5sRp7718DxNY1QpK8nXJVQ4BG1oTA6w0+pK+wxVIl6
    MYSQL_USER: AgAv8USBDbvYQ1VQ4JLhbmq/nmawhS8EUkPAShXBOpGymT1SfhrCJXaz4g1hIL3nqH2s0Ceu1I+gXeayVFWqzHOR/Vf+GncMhCDKaspoalQzrIKHnylbOEtjc6+nAKbHPraFOA/Nsh9iWVe4QaxyRtPrdVWg+Rip1YyS/vVBlJv7zACgaV5ivsBEy64sP/lrHekpgdVvm4/waS++TkgAv9m+Q9KKDwNldIwYt+KgjbulHbWDB1R1Nzg8M9Rl7IHc/aeaTyN4p8F1ZGU60yOW6oIEChbJyaCIhCvtDPhuncwEotJ4ExNAjFeG7Za1z7hpSzJG0qLt6Mps5Zcj/pCBcDrAGh5HIyPgyKZNHyShEV/YZqUffNq139BlMZ70a6iuIYMGy42z1FCsFXD/JLPfpLfVHGXBaW7gtfx6CEtdGh8Jqi5y/Wue9UeEckst1qCjvKiqh6kp+B3Pi9GaMrDvPSJhXNicNVf3QoLqHSj0m0JVaL8YUzeIziMcKY+G59nIteSL1bphkdFrMxjHafFt+uSaBUnYMczvUjhqSEWGTcZQPyE6EB8FWgmrDPygvZw6yCglWFLwHdKjSwEins5E1DN8Ced8M7d+lLUw6tKxc34c6YByWLVw6JLc/uNoTBpStZ8nYugVrdb8DP4RypKlKkSYcaxnF6mQUX5gKvKY/r3LXyzwpsbSoEPugnqt2tPUXPIkvTEM
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: default
