apiVersion: v2
name: longhorn
description: Longhorn
type: application
version: 1.5.3
appVersion: "1.5.3"

dependencies:
  - name: longhorn
    repository: https://charts.longhorn.io
    version: 1.5.3
    alias: longhorn
